/* Generated by `re stage6` (sha256 352a6e34). dma64 layout (C3: brcmsmac/b43). */
#ifndef BRCM_DMA_H
#define BRCM_DMA_H

#define BCM_DMA64_CONTROL 0x00
#define BCM_DMA64_STATUS 0x04
#define BCM_DMA64_ADDRLOW 0x08
#define BCM_DMA64_ADDRHIGH 0x0C

#define BCM_DMA_DESC_SIZE 16
#define BCM_DMA_RING_ALIGN 0x2000

#define BCM_D11_INTMASK 0x012C
#define BCM_DMA_WIDTH_32 0x20
#define BCM_DMA_WIDTH_64 0x40

#endif /* BRCM_DMA_H */
