/* Generated by `re stage6` from wlc_hybrid.o_shipped (sha256 352a6e34).
* Legacy rate values are in 500 kbps units; 0x80 marks an 11b (CCK) rate.
* Do not edit by hand. */
#ifndef BRCM_RATES_H
#define BRCM_RATES_H

/* 802.11b (CCK) */
#define BRCM_RATE_1 0x02
#define BRCM_RATE_2 0x04
#define BRCM_RATE_5_5 0x0B
#define BRCM_RATE_11 0x16

/* 802.11a/g (OFDM) */
#define BRCM_RATE_6 0x0C
#define BRCM_RATE_9 0x12
#define BRCM_RATE_12 0x18
#define BRCM_RATE_18 0x24
#define BRCM_RATE_24 0x30
#define BRCM_RATE_36 0x48
#define BRCM_RATE_48 0x60
#define BRCM_RATE_54 0x6C

/* TID -> FIFO (802.11e) */
#define BRCM_TID2FIFO {1,0,0,1,2,2,3,3}
/* FIFO -> AC (AC_BE=0,AC_BK=1,AC_VI=2,AC_VO=3) */
#define BRCM_FIFO2AC {1,0,2,3}

/* Channel rules (MHz) */
#define BRCM_2GHZ_BASE_MHZ 2407
#define BRCM_5GHZ_BASE_MHZ 5000
#define BRCM_CH_SPACING_MHZ 5
#define BRCM_CH14_MHZ 2484

#endif /* BRCM_RATES_H */
