/* Generated by `re stage8` (sha256 352a6e34). mac80211 mapping. */
#ifndef BRCM_WLC_H
#define BRCM_WLC_H

/* ieee80211_ops .tx -> wlc_sendpkt */
/* ieee80211_ops .start -> wlc_up */
/* ieee80211_ops .stop -> wlc_down */
/* ieee80211_ops .add_interface -> wlc_set_ssid */
/* ieee80211_ops .remove_interface -> wlc_set_ssid */
/* ieee80211_ops .config -> wlc_set_chanspec */
/* ieee80211_ops .bss_info_changed -> wlc_set_bssid */
/* ieee80211_ops .configure_filter -> wlc_mac_promisc */
/* ieee80211_ops .set_key -> wlc_key_insert */
/* ieee80211_ops .wake_tx_queue -> wlc_txfifo */
/* ieee80211_ops .add_chanctx -> wlc_set_chanspec */
/* ieee80211_ops .remove_chanctx -> wlc_set_chanspec */
/* ieee80211_ops .change_chanctx -> wlc_set_chanspec */

#endif /* BRCM_WLC_H */
